CREATE TABLE CATEGORIA(
	CAT_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	CAT_NOME VARCHAR(50) NOT NULL
)Engine=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO CATEGORIA (CAT_NOME) VALUES ('Lazer');
INSERT INTO CATEGORIA (CAT_NOME) VALUES ('Alimentação');
INSERT INTO CATEGORIA (CAT_NOME) VALUES ('Supermercado');
INSERT INTO CATEGORIA (CAT_NOME) VALUES ('Farmácia');
INSERT INTO CATEGORIA (CAT_NOME) VALUES ('Outros');