CREATE TABLE PESSOA(
	PES_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	PES_NOME VARCHAR(255) NOT NULL,
	PES_ATIVO TINYINT NOT NULL DEFAULT 1,
	PES_END_LOGRADOURO VARCHAR(255),
	PES_END_NUMERO VARCHAR(10),
	PES_END_COMPLEMENTO VARCHAR(30),
	PES_END_BAIRRO VARCHAR(30),
	PES_END_CEP VARCHAR(9),
	PES_END_CIDADE VARCHAR(50),
	PES_END_UF CHAR(2)
	
)Engine=InnoDB DEFAULT CHARSET=utf8;

