CREATE TABLE LANCAMENTO (
	LANC_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	LANC_DESCRICAO VARCHAR(50) NOT NULL,
	LANC_DT_VENCIMENTO DATE NOT NULL,
	LANC_DT_PAGAMENTO DATE,
	LANC_VALOR DECIMAL(10,2) NOT NULL,
	LANC_OBSERVACAO VARCHAR(200),
	LANC_TIPO CHAR(7) NOT NULL,
	CAT_ID BIGINT(20) NOT NULL,
	PES_ID BIGINT(20) NOT NULL,
	FOREIGN KEY (CAT_ID) REFERENCES CATEGORIA(CAT_ID),
	FOREIGN KEY (PES_ID) REFERENCES PESSOA(PES_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO PESSOA (PES_NOME, PES_END_LOGRADOURO, PES_END_NUMERO, PES_END_COMPLEMENTO, PES_END_BAIRRO, PES_END_CEP, PES_END_CIDADE, PES_END_UF, PES_ATIVO) values ('João Silva', 'Rua do Abacaxi', '10', null, 'Brasil', '38.400-12', 'Uberlândia', 'MG', true);
INSERT INTO PESSOA (PES_NOME, PES_END_LOGRADOURO, PES_END_NUMERO, PES_END_COMPLEMENTO, PES_END_BAIRRO, PES_END_CEP, PES_END_CIDADE, PES_END_UF, PES_ATIVO) values ('Maria Rita', 'Rua do Sabiá', '110', 'Apto 101', 'Colina', '11.400-12', 'Ribeirão Preto', 'SP', true);
INSERT INTO PESSOA (PES_NOME, PES_END_LOGRADOURO, PES_END_NUMERO, PES_END_COMPLEMENTO, PES_END_BAIRRO, PES_END_CEP, PES_END_CIDADE, PES_END_UF, PES_ATIVO) values ('Pedro Santos', 'Rua da Bateria', '23', null, 'Morumbi', '54.212-12', 'Goiânia', 'GO', true);
INSERT INTO PESSOA (PES_NOME, PES_END_LOGRADOURO, PES_END_NUMERO, PES_END_COMPLEMENTO, PES_END_BAIRRO, PES_END_CEP, PES_END_CIDADE, PES_END_UF, PES_ATIVO) values ('Ricardo Pereira', 'Rua do Motorista', '123', 'Apto 302', 'Aparecida', '38.400-12', 'Salvador', 'BA', true);
INSERT INTO PESSOA (PES_NOME, PES_END_LOGRADOURO, PES_END_NUMERO, PES_END_COMPLEMENTO, PES_END_BAIRRO, PES_END_CEP, PES_END_CIDADE, PES_END_UF, PES_ATIVO) values ('Josué Mariano', 'Av Rio Branco', '321', null, 'Jardins', '56.400-12', 'Natal', 'RN', true);
INSERT INTO PESSOA (PES_NOME, PES_END_LOGRADOURO, PES_END_NUMERO, PES_END_COMPLEMENTO, PES_END_BAIRRO, PES_END_CEP, PES_END_CIDADE, PES_END_UF, PES_ATIVO) values ('Pedro Barbosa', 'Av Brasil', '100', null, 'Tubalina', '77.400-12', 'Porto Alegre', 'RS', true);
INSERT INTO PESSOA (PES_NOME, PES_END_LOGRADOURO, PES_END_NUMERO, PES_END_COMPLEMENTO, PES_END_BAIRRO, PES_END_CEP, PES_END_CIDADE, PES_END_UF, PES_ATIVO) values ('Henrique Medeiros', 'Rua do Sapo', '1120', 'Apto 201', 'Centro', '12.400-12', 'Rio de Janeiro', 'RJ', true);
INSERT INTO PESSOA (PES_NOME, PES_END_LOGRADOURO, PES_END_NUMERO, PES_END_COMPLEMENTO, PES_END_BAIRRO, PES_END_CEP, PES_END_CIDADE, PES_END_UF, PES_ATIVO) values ('Carlos Santana', 'Rua da Manga', '433', null, 'Centro', '31.400-12', 'Belo Horizonte', 'MG', true);
INSERT INTO PESSOA (PES_NOME, PES_END_LOGRADOURO, PES_END_NUMERO, PES_END_COMPLEMENTO, PES_END_BAIRRO, PES_END_CEP, PES_END_CIDADE, PES_END_UF, PES_ATIVO) values ('Leonardo Oliveira', 'Rua do Músico', '566', null, 'Segismundo Pereira', '38.400-00', 'Uberlândia', 'MG', true);
INSERT INTO PESSOA (PES_NOME, PES_END_LOGRADOURO, PES_END_NUMERO, PES_END_COMPLEMENTO, PES_END_BAIRRO, PES_END_CEP, PES_END_CIDADE, PES_END_UF, PES_ATIVO) values ('Isabela Martins', 'Rua da Terra', '1233', 'Apto 10', 'Vigilato', '99.400-12', 'Manaus', 'AM', true);


INSERT INTO LANCAMENTO (LANC_DESCRICAO, LANC_DT_VENCIMENTO, LANC_DT_PAGAMENTO, LANC_VALOR, LANC_OBSERVACAO, LANC_TIPO, CAT_ID, PES_ID) values ('Salário mensal', '2017-06-10', null, 6500.00, 'Distribuição de lucros', 'RECEITA', 1, 1);
INSERT INTO LANCAMENTO (LANC_DESCRICAO, LANC_DT_VENCIMENTO, LANC_DT_PAGAMENTO, LANC_VALOR, LANC_OBSERVACAO, LANC_TIPO, CAT_ID, PES_ID) values ('Bahamas', '2017-02-10', '2017-02-10', 100.32, null, 'DESPESA', 2, 2);
INSERT INTO LANCAMENTO (LANC_DESCRICAO, LANC_DT_VENCIMENTO, LANC_DT_PAGAMENTO, LANC_VALOR, LANC_OBSERVACAO, LANC_TIPO, CAT_ID, PES_ID) values ('Top Club', '2017-06-10', null, 120, null, 'RECEITA', 3, 3);
INSERT INTO LANCAMENTO (LANC_DESCRICAO, LANC_DT_VENCIMENTO, LANC_DT_PAGAMENTO, LANC_VALOR, LANC_OBSERVACAO, LANC_TIPO, CAT_ID, PES_ID) values ('CEMIG', '2017-02-10', '2017-02-10', 110.44, 'Geração', 'RECEITA', 3, 4);
INSERT INTO LANCAMENTO (LANC_DESCRICAO, LANC_DT_VENCIMENTO, LANC_DT_PAGAMENTO, LANC_VALOR, LANC_OBSERVACAO, LANC_TIPO, CAT_ID, PES_ID) values ('DMAE', '2017-06-10', null, 200.30, null, 'DESPESA', 3, 5);
INSERT INTO LANCAMENTO (LANC_DESCRICAO, LANC_DT_VENCIMENTO, LANC_DT_PAGAMENTO, LANC_VALOR, LANC_OBSERVACAO, LANC_TIPO, CAT_ID, PES_ID) values ('Extra', '2017-03-10', '2017-03-10', 1010.32, null, 'RECEITA', 4, 6);
INSERT INTO LANCAMENTO (LANC_DESCRICAO, LANC_DT_VENCIMENTO, LANC_DT_PAGAMENTO, LANC_VALOR, LANC_OBSERVACAO, LANC_TIPO, CAT_ID, PES_ID) values ('Bahamas', '2017-06-10', null, 500, null, 'RECEITA', 1, 7);
INSERT INTO LANCAMENTO (LANC_DESCRICAO, LANC_DT_VENCIMENTO, LANC_DT_PAGAMENTO, LANC_VALOR, LANC_OBSERVACAO, LANC_TIPO, CAT_ID, PES_ID) values ('Top Club', '2017-03-10', '2017-03-10', 400.32, null, 'DESPESA', 4, 8);
INSERT INTO LANCAMENTO (LANC_DESCRICAO, LANC_DT_VENCIMENTO, LANC_DT_PAGAMENTO, LANC_VALOR, LANC_OBSERVACAO, LANC_TIPO, CAT_ID, PES_ID) values ('Despachante', '2017-06-10', null, 123.64, 'Multas', 'DESPESA', 3, 9);
INSERT INTO LANCAMENTO (LANC_DESCRICAO, LANC_DT_VENCIMENTO, LANC_DT_PAGAMENTO, LANC_VALOR, LANC_OBSERVACAO, LANC_TIPO, CAT_ID, PES_ID) values ('Pneus', '2017-04-10', '2017-04-10', 665.33, null, 'RECEITA', 5, 10);
INSERT INTO LANCAMENTO (LANC_DESCRICAO, LANC_DT_VENCIMENTO, LANC_DT_PAGAMENTO, LANC_VALOR, LANC_OBSERVACAO, LANC_TIPO, CAT_ID, PES_ID) values ('Café', '2017-06-10', null, 8.32, null, 'DESPESA', 1, 5);
INSERT INTO LANCAMENTO (LANC_DESCRICAO, LANC_DT_VENCIMENTO, LANC_DT_PAGAMENTO, LANC_VALOR, LANC_OBSERVACAO, LANC_TIPO, CAT_ID, PES_ID) values ('Eletrônicos', '2017-04-10', '2017-04-10', 2100.32, null, 'DESPESA', 5, 4);
INSERT INTO LANCAMENTO (LANC_DESCRICAO, LANC_DT_VENCIMENTO, LANC_DT_PAGAMENTO, LANC_VALOR, LANC_OBSERVACAO, LANC_TIPO, CAT_ID, PES_ID) values ('Instrumentos', '2017-06-10', null, 1040.32, null, 'DESPESA', 4, 3);
INSERT INTO LANCAMENTO (LANC_DESCRICAO, LANC_DT_VENCIMENTO, LANC_DT_PAGAMENTO, LANC_VALOR, LANC_OBSERVACAO, LANC_TIPO, CAT_ID, PES_ID) values ('Café', '2017-04-10', '2017-04-10', 4.32, null, 'DESPESA', 4, 2);
INSERT INTO LANCAMENTO (LANC_DESCRICAO, LANC_DT_VENCIMENTO, LANC_DT_PAGAMENTO, LANC_VALOR, LANC_OBSERVACAO, LANC_TIPO, CAT_ID, PES_ID) values ('Lanche', '2017-06-10', null, 10.20, null, 'DESPESA', 4, 1);